package compose

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"switchyard.dev/switchyard/internal/runtime/domain"
)

func writePortOverride(directory string, project domain.ProjectRuntime) (string, error) {
	if directory == "" {
		return "", errors.New("compose worktree artifact directory is not configured")
	}
	contents, err := portOverrideYAML(project)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(directory, 0o700); err != nil {
		return "", fmt.Errorf("create Compose worktree artifact directory: %w", err)
	}
	digest := sha256.Sum256([]byte(project.ProjectID + "\x00" + project.ManifestHash))
	path := filepath.Join(directory, "ports-"+hex.EncodeToString(digest[:12])+".yaml")
	temporary, err := os.CreateTemp(directory, ".ports-*.yaml")
	if err != nil {
		return "", fmt.Errorf("create Compose port overlay: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return "", err
	}
	if _, err := temporary.WriteString(contents); err != nil {
		_ = temporary.Close()
		return "", fmt.Errorf("write Compose port overlay: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return "", err
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return "", fmt.Errorf("publish Compose port overlay: %w", err)
	}
	return path, nil
}

func portOverrideYAML(project domain.ProjectRuntime) (string, error) {
	if project.Compose == nil {
		return "", errors.New("compose worktree port overlay requires a Compose runtime")
	}
	services := make(map[string][]string)
	serviceNames := make(map[string]string, len(project.Services))
	for _, service := range project.Services {
		serviceNames[service.ID] = service.RuntimeName
	}
	for portID, hostPort := range project.Compose.PortOverrides {
		declaration, exists := project.Ports[portID]
		if !exists {
			return "", fmt.Errorf("worktree port lease references unknown manifest port %q", portID)
		}
		runtimeName := serviceNames[declaration.Service]
		if runtimeName == "" {
			return "", fmt.Errorf("worktree port lease %q has no Compose service", portID)
		}
		protocol := declaration.Protocol
		if protocol == "" {
			protocol = "tcp"
		}
		binding := fmt.Sprintf("127.0.0.1:%d:%d/%s", hostPort, declaration.Target, protocol)
		services[runtimeName] = append(services[runtimeName], binding)
	}
	names := make([]string, 0, len(services))
	for name := range services {
		names = append(names, name)
	}
	sort.Strings(names)
	var document strings.Builder
	document.WriteString("# Generated by Switchyard from exact worktree port leases. No secrets.\nservices:\n")
	for _, name := range names {
		document.WriteString("  ")
		document.WriteString(strconv.Quote(name))
		document.WriteString(":\n    ports: !override\n")
		sort.Strings(services[name])
		for _, binding := range services[name] {
			document.WriteString("      - ")
			document.WriteString(strconv.Quote(binding))
			document.WriteByte('\n')
		}
	}
	return document.String(), nil
}
