// Command repositorycheck enforces legal metadata, generated-source headers,
// and a local high-confidence credential scan.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type finding struct {
	path   string
	line   int
	reason string
}

func (f finding) String() string {
	if f.line == 0 {
		return fmt.Sprintf("%s: %s", f.path, f.reason)
	}
	return fmt.Sprintf("%s:%d: %s", f.path, f.line, f.reason)
}

var secretPatterns = []struct {
	name    string
	pattern *regexp.Regexp
}{
	{name: "private key", pattern: regexp.MustCompile(`-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----`)},
	{name: "AWS access key", pattern: regexp.MustCompile(`\bAKIA[0-9A-Z]{16}\b`)},
	{name: "GitHub token", pattern: regexp.MustCompile(`\bgh[pousr]_[A-Za-z0-9]{30,}\b`)},
	{name: "OpenAI-style key", pattern: regexp.MustCompile(`\bsk-[A-Za-z0-9_-]{20,}\b`)},
	{name: "Slack token", pattern: regexp.MustCompile(`\bxox[baprs]-[A-Za-z0-9-]{20,}\b`)},
}

func main() {
	findings, err := inspect(".")
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	for _, item := range findings {
		_, _ = fmt.Fprintln(os.Stderr, item)
	}
	if len(findings) > 0 {
		os.Exit(1)
	}
}

func inspect(root string) ([]finding, error) {
	var findings []finding
	for _, requirement := range []struct {
		path     string
		contains []string
	}{
		{path: "LICENSE", contains: []string{"Apache License", "Version 2.0, January 2004"}},
		{path: "NOTICE", contains: []string{"Switchyard", "Switchyard contributors"}},
		{path: ".reuse/dep5", contains: []string{"Format:", "Files: *", "License: Apache-2.0"}},
		{path: "package.json", contains: []string{`"license": "Apache-2.0"`}},
		{path: "desktop/src-tauri/Cargo.toml", contains: []string{`license = "Apache-2.0"`}},
	} {
		contents, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(requirement.path)))
		if err != nil {
			findings = append(findings, finding{path: requirement.path, reason: "required legal metadata is missing"})
			continue
		}
		for _, marker := range requirement.contains {
			if !bytes.Contains(contents, []byte(marker)) {
				findings = append(findings, finding{path: requirement.path, reason: fmt.Sprintf("required legal marker %q is missing", marker)})
			}
		}
	}

	for _, generated := range []struct {
		path   string
		marker string
	}{
		{path: "internal/transport/contract/generated/api.gen.go", marker: "Code generated"},
		{path: "internal/platform/sqlite/generated/models.go", marker: "Code generated by sqlc. DO NOT EDIT."},
		{path: "web/src/api/generated/types.gen.ts", marker: "auto-generated"},
	} {
		contents, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(generated.path)))
		if err != nil || !bytes.Contains(firstBytes(contents, 512), []byte(generated.marker)) {
			findings = append(findings, finding{path: generated.path, reason: "generated-source provenance header is missing"})
		}
	}

	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() && ignoredDirectory(entry.Name()) && path != root {
			return filepath.SkipDir
		}
		if entry.IsDir() || !scannable(path) {
			return nil
		}
		items, scanErr := scanSecrets(path)
		findings = append(findings, items...)
		return scanErr
	})
	if err != nil {
		return nil, fmt.Errorf("scan repository: %w", err)
	}
	sort.Slice(findings, func(i, j int) bool { return findings[i].String() < findings[j].String() })
	return findings, nil
}

func ignoredDirectory(name string) bool {
	switch name {
	case ".git", ".cache", ".switchyard-data", "bin", "coverage", "dist", "node_modules", "playwright-report", "target", "test-results":
		return true
	default:
		return false
	}
}

func scannable(path string) bool {
	switch filepath.Ext(path) {
	case ".go", ".rs", ".ts", ".vue", ".js", ".mjs", ".json", ".yaml", ".yml", ".toml", ".md", ".sh", ".sql", ".env":
		return true
	default:
		return false
	}
}

func scanSecrets(path string) ([]finding, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()
	var findings []finding
	scanner := bufio.NewScanner(file)
	buffer := make([]byte, 64<<10)
	scanner.Buffer(buffer, 1<<20)
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := scanner.Text()
		if allowedFixtureLine(line) {
			continue
		}
		for _, candidate := range secretPatterns {
			if candidate.pattern.MatchString(line) {
				findings = append(findings, finding{path: filepath.ToSlash(path), line: lineNumber, reason: "possible " + candidate.name})
			}
		}
	}
	if err := scanner.Err(); err != nil && !errors.Is(err, bufio.ErrTooLong) {
		return findings, err
	}
	return findings, nil
}

func allowedFixtureLine(line string) bool {
	lower := strings.ToLower(line)
	return strings.Contains(lower, "fixture") || strings.Contains(lower, "canary") ||
		strings.Contains(lower, "never-return") || strings.Contains(lower, "never-send") ||
		strings.Contains(line, "regexp.MustCompile")
}

func firstBytes(value []byte, maximum int) []byte {
	if len(value) <= maximum {
		return value
	}
	return value[:maximum]
}
