import { execFileSync } from 'node:child_process'
import { mkdtemp, readFile, rm, writeFile, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { docsRoot, repositoryRoot } from './paths'

const verified = '2026-07-17'

async function generateCLIReference(binary: string): Promise<string> {
  const source = await readFile(resolve(repositoryRoot, 'internal/transport/cli/schema_command.go'), 'utf8')
  const block = /var cliCommands = \[\]string\{([\s\S]*?)\n\}/.exec(source)?.[1]
  if (!block) throw new Error('could not find cliCommands in schema_command.go')
  const commands = [...block.matchAll(/"([a-z.]+)"/g)].map((match) => match[1]).filter((value): value is string => Boolean(value))
  const sections = commands.map((command) => {
    const schema = execFileSync(binary, ['schema', 'cli', command], { cwd: repositoryRoot, encoding: 'utf8' }).trim()
    return `## \`${command}\`\n\n\`\`\`json\n${schema}\n\`\`\``
  })
  return `---
title: Generated CLI envelope schemas
description: Versioned command output schemas emitted by the production Switchyard binary.
category: reference
audience: [integrator, contributor]
since: 1.0.0
lastVerified: ${verified}
---

This page is generated by building **cmd/switchyard** and invoking the schema
subcommand for every command registered by the binary.
Do not edit it manually.

${sections.join('\n\n')}
`
}

async function generateManifestReference(): Promise<string> {
  const schema = JSON.parse(await readFile(resolve(repositoryRoot, 'internal/manifest/schema/project.schema.json'), 'utf8')) as {
    $id?: string
    $ref?: string
    title?: string
    properties?: Record<string, { description?: string; type?: string; $ref?: string }>
    required?: string[]
    $defs?: Record<string, {
      properties?: Record<string, { description?: string; type?: string; $ref?: string }>
      required?: string[]
    }>
  }
  const rootName = schema.$ref?.match(/^#\/\$defs\/(.+)$/)?.[1]
  const root = rootName ? schema.$defs?.[rootName] : schema
  if (!root?.properties) throw new Error('Project manifest schema root has no properties')
  const rows = Object.entries(root.properties).map(([name, value]) => {
    const shape = value.type ?? value.$ref?.split('/').at(-1) ?? 'schema'
    return `| \`${name}\` | ${shape} | ${root.required?.includes(name) ? 'yes' : 'no'} | ${value.description ?? ''} |`
  })
  return `---
title: Generated project manifest schema index
description: Top-level project manifest fields generated from the committed canonical JSON Schema.
category: reference
audience: [user, integrator, contributor]
since: 1.0.0
lastVerified: ${verified}
---

Source schema: [\`${schema.$id ?? 'internal/manifest/schema/project.schema.json'}\`](/docs/manifest-reference/).
Do not edit this generated page manually.

| Field | Shape | Required | Description |
|---|---|:---:|---|
${rows.join('\n')}
`
}

async function generateSettingsReference(): Promise<string> {
  const source = await readFile(resolve(repositoryRoot, 'internal/settings/domain/settings.go'), 'utf8')
  const fields = [...source.matchAll(/^\s*(\w+)\s+([^`\n]+)\s+`json:"([^",]+)[^"]*"`/gm)]
  const rows = fields.map((match) => `| \`${match[3]}\` | \`${match[2]?.trim()}\` | \`${match[1]}\` |`)
  return `---
title: Generated settings field index
description: Durable non-secret settings fields generated from the canonical Go domain structs.
category: reference
audience: [user, integrator, contributor]
since: 1.0.0
lastVerified: ${verified}
---

The domain model deliberately contains credential references, never credential
values. Do not edit this generated page manually.

| JSON field | Go shape | Domain field |
|---|---|---|
${rows.join('\n')}
`
}

async function generateMCPReference(): Promise<string> {
  const sources = await Promise.all(
    ['read_tools.go', 'mutation_tools.go'].map((file) =>
      readFile(resolve(repositoryRoot, 'internal/transport/mcpserver', file), 'utf8'),
    ),
  )
  const rows: string[] = []
  for (const source of sources) {
    for (const match of source.matchAll(/(?:readTool|mutationTool)\("(switchyard_[^"]+)",\s*"([^"]+)",\s*"([^"]+)"(?:,\s*"([^"]+)",\s*agents\.Profile(\w+))?/g)) {
      const profile = match[5]?.toLowerCase() ?? 'observe'
      const risk = match[4] ?? 'read-only'
      rows.push(`| \`${match[1]}\` | ${match[2]} | ${profile} | ${risk} | ${match[3]} |`)
    }
  }
  return `---
title: Generated MCP tool index
description: Tool names, profiles, risks, and descriptions generated from the MCP server registration.
category: reference
audience: [user, integrator, contributor]
since: 1.0.0
lastVerified: ${verified}
---

Tools call application services and are omitted when the selected permission
profile cannot use them. Do not edit this generated page manually.

| Tool | Title | Minimum profile | Risk | Purpose |
|---|---|---|---|---|
${rows.sort().join('\n')}
`
}

async function generateOpenAPIReference(): Promise<string> {
  const source = await readFile(resolve(repositoryRoot, 'api/openapi.yaml'), 'utf8')
  const lines = source.split('\n')
  let currentPath = ''
  let method = ''
  const rows: string[] = []
  for (const line of lines) {
    const path = /^ {2}(\/[^:]+):$/.exec(line)?.[1]
    if (path) { currentPath = path; continue }
    const methodMatch = /^ {4}(get|post|put|patch|delete):$/.exec(line)?.[1]
    if (methodMatch) { method = methodMatch.toUpperCase(); continue }
    const operation = /^ {6}operationId: (\S+)$/.exec(line)?.[1]
    if (operation && currentPath && method) rows.push(`| \`${method}\` | \`/api/v1${currentPath}\` | \`${operation}\` |`)
  }
  return `---
title: Generated local REST API index
description: Versioned local control-plane operations generated from the canonical OpenAPI contract.
category: reference
audience: [integrator, contributor]
since: 1.0.0
lastVerified: ${verified}
---

The browser, desktop, and local clients use this contract through authenticated
local transports. This is not a public network API. Do not edit this generated
page manually.

| Method | Path | Operation ID |
|---|---|---|
${rows.join('\n')}
`
}

async function generatePluginReference(): Promise<string> {
  const source = await readFile(resolve(repositoryRoot, 'sdk/plugin/protocol.go'), 'utf8')
  const version = /ProtocolVersion = "([^"]+)"/.exec(source)?.[1]
  const manifest = /ManifestVersion = "([^"]+)"/.exec(source)?.[1]
  const capabilities = [...source.matchAll(/Capability\w+\s+Capability = "([^"]+)"/g)].map((match) => match[1])
  return `---
title: Generated plugin protocol index
description: Protocol identity and capabilities generated from the public Go plugin SDK.
category: reference
audience: [integrator, contributor]
since: 1.0.0
lastVerified: ${verified}
---

- Protocol: \`${version ?? 'unknown'}\`
- Manifest: \`${manifest ?? 'unknown'}\`
- Transport: newline-delimited JSON-RPC over stdio

## Capabilities

${capabilities.map((capability) => `- \`${capability}\``).join('\n')}

Plugins receive only explicitly granted scopes and run outside the daemon
process. Do not edit this generated page manually.
`
}

export async function generateReference(): Promise<void> {
  const output = resolve(docsRoot, 'generated')
  await mkdir(output, { recursive: true })
  const temporary = await mkdtemp(join(tmpdir(), 'switchyard-site-reference-'))
  const binary = resolve(temporary, 'switchyard')
  try {
    execFileSync('go', ['build', '-trimpath', '-o', binary, './cmd/switchyard'], {
      cwd: repositoryRoot,
      env: { ...process.env, GOCACHE: resolve(repositoryRoot, '.cache/go-build') },
      stdio: 'inherit',
    })
    const files = new Map<string, string>([
      ['cli-schemas.md', await generateCLIReference(binary)],
      ['manifest-schema.md', await generateManifestReference()],
      ['settings-schema.md', await generateSettingsReference()],
      ['mcp-tools.md', await generateMCPReference()],
      ['openapi.md', await generateOpenAPIReference()],
      ['plugin-protocol.md', await generatePluginReference()],
    ])
    for (const [name, content] of files) await writeFile(resolve(output, name), content, 'utf8')
  } finally {
    await rm(temporary, { recursive: true, force: true })
  }
}

if (import.meta.url === `file://${process.argv[1]}`) await generateReference()
